# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(db_index=True, max_length=80, unique=True)),
                ('original_url', models.URLField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=80, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
